### ISSUE TITLE
🐛 rquest-omop-worker pandas dependency tries and fails to use numpy 2.x

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/rquest-tools#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using recently published container images or building / running from source, rquest-omop-worker's pip install will install numpy 2.x (breaking changes vs 1.x) which will not work with the current codebase. This is due to pandas not constraining the version of its numpy dependency.

error:

```
Traceback (most recent call last):
  File "/usr/local/bin/rquest-omop-worker", line 5, in <module>
    from scripts.worker import main
  File "/usr/local/lib/python3.10/site-packages/scripts/worker.py", line 7, in <module>
    from rquest_omop_worker import query_solvers
  File "/usr/local/lib/python3.10/site-packages/rquest_omop_worker/query_solvers.py", line 5, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/local/lib/python3.10/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/usr/local/lib/python3.10/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/usr/local/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

### Expected Behavior

rquest-omop-worker should work correctly, and not error due to changes in numpy's API.

### Steps To Reproduce

1. pull the latest docker image of `hutchstack/rquest-omop-worker`
2. Prepare an input json for a distribution or availability query
3. Prepare a .env file with DB connection details
4. Run the image with the prepared files e.g.:
    - `sudo docker run -v .:/var/opt/worker --env-file .env -it hutchstack/rquest-omop-worker rquest-omop-worker -d --body /var/opt/worker/input.json -o /var/opt/worker/output.json`

### Environment

```markdown
- OS: Fedora 40, Ubuntu 22.04
```

### I'm part of a Project Team

DRS

### Anything else?

The fix is to add an explicitly versioned numpy dependency, per: https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from

### Are you willing to contribute to resolve this issue?

✅ Yes, me or my team intend to do the development.

**Comment by beforan** [comment]
confirmed fixed by #53 
![image](https://github.com/user-attachments/assets/4bbea1de-320b-421e-a5ea-85781249fb24)
